name: Trigger auto deployment for opengpts-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/opengpts-app-AutoDeployTrigger-28ff0f4c-7572-4155-86fc-fec48be9afd7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OPENGPTSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENGPTSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPENGPTSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: opengpts.azurecr.io
          registryUsername: ${{ secrets.OPENGPTSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OPENGPTSAPP_REGISTRY_PASSWORD }}
          containerAppName: opengpts-app
          resourceGroup: opengpts
          imageToBuild: opengpts.azurecr.io/opengpts-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


